using MediatR;
using RealLifeServer.Application.Channels.Dtos;
using RealLifeServer.Application.Common.Exceptions;
using RealLifeServer.Application.Common.Interfaces;
using RealLifeServer.Application.Common.Utils;
using RealLifeServer.Domain.Entities;
using RealLifeServer.Domain.Enums;

namespace RealLifeServer.Application.Channels.Commands;

public sealed record AddStreamDestinationCommand(
    Guid ChannelId,
    StreamPlatform Platform,
    string RtmpUrl,
    string StreamKeyPlainText) : IRequest<ChannelDto>;

public sealed class AddStreamDestinationCommandHandler(
    IChannelRepository channels,
    IApplicationDbContext db,
    IEncryptionService encryption,
    IStreamOrchestrator orchestrator)
    : IRequestHandler<AddStreamDestinationCommand, ChannelDto>
{
    public async Task<ChannelDto> Handle(AddStreamDestinationCommand request, CancellationToken ct)
    {
        if (!RtmpUrlValidator.IsValid(request.RtmpUrl))
        {
            throw new ValidationException($"\"{request.RtmpUrl}\" is not a valid rtmp:// or rtmps:// URL.");
        }
        if (string.IsNullOrWhiteSpace(request.StreamKeyPlainText))
        {
            throw new ValidationException("A stream key is required.");
        }

        var channel = await channels.GetByIdAsync(request.ChannelId, ct)
            ?? throw new NotFoundException(nameof(Channel), request.ChannelId);

        // Added via the DbSet, not channel.Destinations.Add(...): StreamDestination.Id is a
        // client-generated, non-default Guid (BaseEntity), and Npgsql's EF Core provider
        // configures Guid keys as store-generated by convention. Adding a new entity only to an
        // already-tracked parent's collection navigation makes EF Core's DetectChanges graph-walk
        // treat it as an *existing* row being reattached (EntityState.Modified) rather than a new
        // one - it generates an UPDATE keyed on the not-yet-existing Id, which matches zero rows
        // and throws DbUpdateConcurrencyException. db.StreamDestinations.Add(...) unambiguously
        // marks it Added; EF's relationship fixup still populates channel.Destinations from the
        // FK match, so the DTO built below is unaffected.
        var destination = new StreamDestination
        {
            ChannelId = channel.Id,
            Platform = request.Platform,
            RtmpUrl = request.RtmpUrl,
            StreamKeyEncrypted = encryption.Encrypt(request.StreamKeyPlainText),
            DisplayOrder = (short)channel.Destinations.Count
        };
        db.StreamDestinations.Add(destination);

        await db.SaveChangesAsync(ct);

        // New destinations start enabled (see StreamDestination.IsEnabled's default), so they
        // always change the compositor's active output set - restart so the running FFmpeg
        // process (its tee target list is fixed at process start) picks it up. Controlled: the
        // next SceneMonitorHostedService tick restarts it, same as RegenerateStreamKeyCommand.
        await orchestrator.StopEncoderAsync(channel.Id, ct);

        return ChannelDto.FromEntity(channel);
    }
}
